---
titile: "Data Frames"
author: "Mohtasim Hadi Rafi"
date: "22 May, 2024"
output: "html_document"
---

# R Notebook, Data Frames, and swirl

## Reproducible Research

Would not it be great if the authors would provide the data and the statistical analysis in away that would make it easy for you to check and reproduce their results? Thisidea of reproducibility is supported by the document formats of Quarto, RNotebook, R Markdown, and R Sweave.

## Data Frames

Consider the data file college.csv -

```{R}
us.colleges <- read.csv("college.csv")
```

Finding Structure of an R Object-

```{R}
str(us.colleges)
```

We learn that the variable us.colleges contains a so-called data frame containing 777 observations of 19 variables. A data frame is like a spreadsheet with rows and columns. You can pick out certain rows and columns as follows:

```{R}
us.colleges[3, 4]	        # 3rd row and 4th column
us.colleges[3, "Accept"]	# 3rd row and column labelled Accept
us.colleges[3, c(1, 3)]	    # 3rd row and columns 1 and 3
us.colleges[3, ]	        # 3rd row and all columns
us.colleges[3, -4]	        # 3rd row and all columns except the 4th column
us.colleges[3, -c(1, 4)]	# 3rd row and all columns except the 1st
                            # and the 4th column # nolint
```

Suppose you want to modify your data set. Let's store the first four and the last four and the last column of the data set in the variable us.colleges2. What are the variable names of us.colleges2?

```{R}
us.colleges2 <- us.colleges[,c(1:4, 19)]
names(us.colleges2)
```

The variable names are not very descriptive. Let's change the variable names of us.colleges2 to college, private, applied, accepted, graduation.rate. Here, the variable applied records the number of applications received and the variable accepted, the number of applicants accepted.

```{R}
names(us.colleges2) <- c("college", "private", "applied", "accepted", "graduation.rate")
```

Now let's add another column to us.colleges2 called "acception.rate" which records the proportion of accepted students.

```{R}
us.colleges2$acception.rate <- us.colleges2$accepted/us.colleges2$applied
```

Let's save the new data using the function write.csv().

```{R}
write.csv(us.colleges2, file="colleges2.csv")
```

Is there a difference between the acceptance rates for private and public colleges? Find the average acceptance rate for private and public colleges separately.

Here is a solution using logical vectors to select the desired colleges.

```{R}
ind.private <- us.colleges2$private == "Yes"
mean(us.colleges2$acception.rate[ind.private])

ind.public <- us.colleges2$private == "No"
mean(us.colleges2$acception.rate[ind.public])
```

A more elegant solution would be to use the R funtion by().

```{R}
by(us.colleges2$acception.rate, us.colleges2$private, mean)
```

It gets tedisous to have to type us.colleges\$college. To avoid this you could use the with() function.

```{R}
with(us.colleges2, by(acception.rate, private, mean))
```

Another approach is to attach and then detach the data frame-

```{R}
attach(us.colleges2)
by(acception.rate, private, mean)
detach(us.colleges2)
```

How many colleges accept at least 90% of all applicants?

```{R}
sum(us.colleges2$acception.rate >= 0.9)
```

Find 10 colleges with the highest acceptance rates.

```{R}
attach(us.colleges2)
ord <- order(acception.rate, decreasing = TRUE)
college[ord][1:10]
detach(us.colleges2)
```

Find all public colleges that have an acception rate of at least 80% and a graduation rate of at least 80%.

```{R}
attach(us.colleges2)
ind <- acception.rate >= 0.8 & graduation.rate >= 80
college[ind]
detach(us.colleges2)
```

## swirl

There are thousands of R libraries available. In fact, there is one that teaches you R programming interactively at your own pace. Install the R package swirl as follows. Open R or RStudio and type

install.packages("swirl")

into the R console and press the Enter key. Then start this learning environment as follows. Type the following, presssing Enter after each line.

library("swirl")
swirl()

Choose the lesson "R Programming" and complete the following seven sections:

1.  Basic Building Blocks
2.  Workspace and Files
3.  Sequences of Numbers
4.  Vectors
5.  Missing Values
6.  Subsetting Vectors
7.  Matrices and Data Frames

At the end of each section you might be asked if you want to send an email to your instructor. Please don't.

For additional help I recommend the lectures given by Mike Marin (see here: <https://www.youtube.com/user/marinstatlectures>). Most of them are short (less than 10 minutes) and to the point.
